export const SYSTEM_CATEGORIES = [
  { slug: 'food', name: 'Food', kind: 'EXPENSE' as const },
  { slug: 'transport', name: 'Transport', kind: 'EXPENSE' as const },
  { slug: 'rent', name: 'Rent', kind: 'EXPENSE' as const },
  { slug: 'utilities', name: 'Utilities', kind: 'EXPENSE' as const },
  { slug: 'internet', name: 'Internet', kind: 'EXPENSE' as const },
  { slug: 'shopping', name: 'Shopping', kind: 'EXPENSE' as const },
  { slug: 'health', name: 'Health', kind: 'EXPENSE' as const },
  { slug: 'education', name: 'Education', kind: 'EXPENSE' as const },
  { slug: 'entertainment', name: 'Entertainment', kind: 'EXPENSE' as const },
  { slug: 'other-expense', name: 'Other', kind: 'EXPENSE' as const },
  { slug: 'salary', name: 'Salary', kind: 'INCOME' as const },
  { slug: 'business', name: 'Business', kind: 'INCOME' as const },
  { slug: 'gift', name: 'Gift', kind: 'INCOME' as const },
  { slug: 'other-income', name: 'Other', kind: 'INCOME' as const },
] as const;

export const DEFAULT_ACCOUNTS = [
  { name: 'Cash', type: 'CASH' as const, isDefault: true },
  { name: 'Bank', type: 'BANK' as const, isDefault: false },
  { name: 'Telebirr', type: 'TELEBIRR' as const, isDefault: false },
  { name: 'M-Pesa', type: 'MPESA' as const, isDefault: false },
  { name: 'Card', type: 'CARD' as const, isDefault: false },
  { name: 'Other', type: 'OTHER' as const, isDefault: false },
] as const;

export const CATEGORY_ALIASES: Record<string, string> = {
  lunch: 'food',
  dinner: 'food',
  breakfast: 'food',
  coffee: 'food',
  restaurant: 'food',
  grocer: 'food',
  taxi: 'transport',
  bus: 'transport',
  fuel: 'transport',
  petrol: 'transport',
  'ride': 'transport',
  house: 'rent',
  electric: 'utilities',
  electricity: 'utilities',
  water: 'utilities',
  wifi: 'internet',
  data: 'internet',
  clothes: 'shopping',
  market: 'shopping',
  hospital: 'health',
  medicine: 'health',
  school: 'education',
  movie: 'entertainment',
  wage: 'salary',
  pay: 'salary',
  ምሳ: 'food',
  እራት: 'food',
  ቁርስ: 'food',
  ቡና: 'food',
  ታክሲ: 'transport',
  አውቶቡስ: 'transport',
  ኪራይ: 'rent',
  ውሃ: 'utilities',
  መብራት: 'utilities',
  ዋይፋይ: 'internet',
  ትምህርት: 'education',
  ደመወዝ: 'salary',
};
