export const FEATURE = {
  AI_NATURAL_LANGUAGE: 'AI_NATURAL_LANGUAGE',
  RULE_BASED_LOGGING: 'RULE_BASED_LOGGING',
  UNLIMITED_TRANSACTIONS: 'UNLIMITED_TRANSACTIONS',
  ADVANCED_REPORTS: 'ADVANCED_REPORTS',
  UNLIMITED_REMINDERS: 'UNLIMITED_REMINDERS',
  SAVINGS_GOALS: 'SAVINGS_GOALS',
  BUDGETS: 'BUDGETS',
  DEBT_TRACKING: 'DEBT_TRACKING',
  IOU_NUDGE: 'IOU_NUDGE',
} as const;

export type Feature = (typeof FEATURE)[keyof typeof FEATURE];

export const FREE_REMINDER_LIMIT = 5;
